version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: 21:00
      timezone: Etc/UTC
    labels:
      - automated
  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: 21:00
      timezone: Etc/UTC
    labels:
      - automated
    groups:
      nix-dependencies:
        patterns:
          - "*"
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: 21:00
      timezone: Etc/UTC
    labels:
      - automated
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
