version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Etc/UTC"
    labels:
      - "automated"
  - package-ecosystem: "nuget"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Etc/UTC"
    labels:
      - "automated"
