version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Etc/UTC"
    labels:
      - "automated"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Etc/UTC"
    labels:
      - "automated"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
  - package-ecosystem: "nix"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Etc/UTC"
    labels:
      - "automated"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
  - package-ecosystem: "nuget"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Etc/UTC"
    labels:
      - "automated"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
