name: 📦️ Check Flake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  pull-requests: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      
      - name: Install Nix
        uses: mdarocha/nix-magic-setup@849d368bdad96581a257094a39b43efb4c0849b3 # v2.0.0
      
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # v13
      
      - name: Run flake check
        run: nix flake check -L